import type{Config,Context}from'@netlify/functions'
import{getUser}from'@netlify/identity'
import{create,esc,list,update,type RecordRow}from'./_shared/airtable'
type Role='admin'|'foreman';type Session={id:string;email:string;name:string;role:Role;crewId?:string}
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{'cache-control':'no-store','x-content-type-options':'nosniff'}})
async function session():Promise<Session|null>{const u=await getUser();if(!u)return null;const raw=u as any,profile=raw.userMetadata||raw.user_metadata||{},email=String(raw.email||'').toLowerCase();if(!email)return null;const adminEmail=String(Netlify.env.get('ADMIN_EMAIL')||'').toLowerCase();return{id:raw.id,email,name:profile.full_name||raw.name||email,role:adminEmail&&email===adminEmail?'admin':'foreman'}}
const links=(r:RecordRow,key:string)=>Array.isArray(r.fields[key])?r.fields[key] as string[]:[]
const name=(r:RecordRow,key:string)=>String(r.fields[key]||'Bez nazwy')
function assignCrew(s:Session,crews:RecordRow[]){if(s.role==='foreman')s.crewId=crews.find(x=>String(x.fields['E-mail brygadzisty']||'').toLowerCase()===s.email)?.id;return s}
async function bootstrap(s:Session){const[sites,buildings,crews,shifts]=await Promise.all([list('Budowy'),list('Budynki'),list('Brygady'),list(Netlify.env.get('AIRTABLE_TIME_TABLE')||'Ewidencja czasu pracy',`AND({Data}=TODAY(),{Brygadzista}='${esc(s.email)}')`)]);assignCrew(s,crews);let allowedCrews=crews,allowedSites=sites,allowedBuildings=buildings;if(s.role==='foreman'){if(!s.crewId)throw new Error('Konto brygadzisty nie ma przypisanej brygady');allowedCrews=crews.filter(x=>x.id===s.crewId);const siteIds=new Set(allowedCrews.flatMap(x=>links(x,'Powiązane budowy')));allowedSites=sites.filter(x=>siteIds.has(x.id));allowedBuildings=buildings.filter(x=>links(x,'Powiązana budowa').some(id=>siteIds.has(id)))}const active=shifts.find(x=>x.fields.Status==='W toku');const finished=shifts.filter(x=>x.fields.Status==='Zakończony').reduce((n,x)=>n+Number(x.fields.Minuty||0),0);return{user:{name:s.name,role:s.role,crewId:s.crewId},sites:allowedSites.map(x=>({id:x.id,name:name(x,'Nazwa budowy')})),buildings:allowedBuildings.map(x=>({id:x.id,name:name(x,'Nazwa / numer budynku'),parentId:links(x,'Powiązana budowa')[0]})),crews:allowedCrews.map(x=>({id:x.id,name:name(x,'Nazwa brygady')})),activeShift:active?{id:active.id,startedAt:String(active.fields.Start)}:undefined,todayMinutes:finished}}
async function start(s:Session){if(s.role==='foreman')assignCrew(s,await list('Brygady'));if(s.role==='foreman'&&!s.crewId)return json({error:'Brak przypisanej brygady'},403);const table=Netlify.env.get('AIRTABLE_TIME_TABLE')||'Ewidencja czasu pracy';const today=new Date().toISOString().slice(0,10);const existing=await list(table,`AND({Data}=TODAY(),{Brygadzista}='${esc(s.email)}',{Status}='W toku')`);if(existing[0])return json({shift:{id:existing[0].id,startedAt:existing[0].fields.Start}});const now=new Date().toISOString();const r=await create(table,{Dzień:`${today} — ${s.name}`,Data:today,...(s.crewId?{Brygada:[s.crewId]}:{}),Brygadzista:s.email,Start:now,Status:'W toku'});return json({shift:{id:r.id,startedAt:now}},201)}
async function stop(s:Session){const table=Netlify.env.get('AIRTABLE_TIME_TABLE')||'Ewidencja czasu pracy';const rows=await list(table,`AND({Data}=TODAY(),{Brygadzista}='${esc(s.email)}',{Status}='W toku')`);if(!rows[0])return json({error:'Brak rozpoczętego dnia pracy'},409);const end=new Date();const minutes=Math.max(1,Math.round((end.getTime()-new Date(String(rows[0].fields.Start)).getTime())/60000));await update(table,rows[0].id,{Koniec:end.toISOString(),Minuty:minutes,Status:'Zakończony'});return json({minutes})}
async function report(req:Request,s:Session){const b=await req.json() as Record<string,unknown>;const meters=Number(b.squareMeters),people=Number(b.people);if(!b.siteId||!b.buildingId||!Number.isFinite(meters)||meters<=0||!Number.isInteger(people)||people<1)return json({error:'Uzupełnij poprawnie wymagane pola'},400);if(s.role==='foreman')assignCrew(s,await list('Brygady'));const crewId=s.role==='foreman'?s.crewId:String(b.crewId||'');if(!crewId)return json({error:'Brak brygady'},400);if(s.role==='foreman'){const shifts=await list(Netlify.env.get('AIRTABLE_TIME_TABLE')||'Ewidencja czasu pracy',`AND({Data}=TODAY(),{Brygadzista}='${esc(s.email)}')`);if(!shifts.length)return json({error:'Najpierw rozpocznij dzisiejszy dzień pracy'},409)}const [crew,building]=await Promise.all([list('Brygady',`RECORD_ID()='${esc(crewId)}'`),list('Budynki',`RECORD_ID()='${esc(String(b.buildingId))}'`)]);if(!crew[0]||!building[0])return json({error:'Nieprawidłowa brygada lub budynek'},403);if(s.role==='foreman'&&crewId!==s.crewId)return json({error:'Brak dostępu do tej brygady'},403);if(!links(crew[0],'Powiązane budowy').includes(String(b.siteId))||!links(building[0],'Powiązana budowa').includes(String(b.siteId)))return json({error:'Budowa nie jest przypisana do tej brygady lub budynku'},403);const today=new Date().toISOString().slice(0,10);const r=await create('Postęp robót',{Raport:`${today} — ${name(crew[0],'Nazwa brygady')}`,Data:today,Budowa:name((await list('Budowy',`RECORD_ID()='${esc(String(b.siteId))}'`))[0],'Nazwa budowy'),'Budynek / etap':name(building[0],'Nazwa / numer budynku'),'Kondygnacja / strefa':String(b.zone||''),'Wykonano m²':meters,'Liczba osób':people,Uwagi:String(b.notes||''),'Powiązana budowa':[b.siteId],Brygada:[crewId],Budynek:[b.buildingId]});if(b.problem)await create('Problemy i dokumentacja',{Temat:`Zgłoszenie ${today}`,"Data zgłoszenia":today,Opis:String(b.problem),'Powiązana budowa':[b.siteId],Brygada:[crewId],Budynek:[b.buildingId]});return json({id:r.id},201)}
export default async(req:Request,context:Context)=>{try{const s=await session();if(!s)return json({error:'Zaloguj się, aby kontynuować'},401);const path=new URL(req.url).pathname;if(req.method==='GET'&&path==='/api/bootstrap')return json(await bootstrap(s));if(req.method==='POST'&&path==='/api/shifts/start')return start(s);if(req.method==='POST'&&path==='/api/shifts/stop')return stop(s);if(req.method==='POST'&&path==='/api/reports')return report(req,s);return json({error:'Nie znaleziono'},404)}catch(e){console.error('API error',context.requestId,e);return json({error:'Nie udało się wykonać operacji. Spróbuj ponownie.'},500)}}
export const config:Config={path:'/api/*'}
