import{useEffect,useMemo,useState}from'react'
import{Building2,ClipboardList,Clock3,FileWarning,HardHat,Plus,Receipt,Save,Users,X}from'lucide-react'
import{api}from'./api'
import type{AdminData,AdminResource,AdminRow,Option}from'./types'

type Field={key:string;label:string;type?:'number'|'date'|'email'|'checkbox'|'textarea'|'select'|'multiselect';options?:()=>Option[]}
type View={label:string;icon:typeof Users;fields:Field[];editable:boolean}
const blank:AdminData={crews:[],sites:[],buildings:[],reports:[],problems:[],shifts:[],invoices:[],costs:[]}

export default function AdminPanel({sites,crews,onMessage}:{sites:Option[];crews:Option[];onMessage:(s:string)=>void}){const[data,setData]=useState<AdminData>(blank);const[active,setActive]=useState<AdminResource>('crews');const[editing,setEditing]=useState<AdminRow>();const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false)
const views=useMemo<Record<AdminResource,View>>(()=>({
crews:{label:'Brygady',icon:Users,editable:true,fields:[{key:'name',label:'Nazwa brygady'},{key:'foreman',label:'Brygadzista'},{key:'email',label:'E-mail logowania',type:'email'},{key:'phone',label:'Telefon'},{key:'people',label:'Liczba osób',type:'number'},{key:'rate',label:'Stawka zł/m²',type:'number'},{key:'status',label:'Status'},{key:'siteIds',label:'Przypisane budowy',type:'multiselect',options:()=>sites},{key:'notes',label:'Uwagi',type:'textarea'}]},
sites:{label:'Budowy',icon:Building2,editable:true,fields:[{key:'name',label:'Nazwa budowy'},{key:'client',label:'Klient / wykonawca'},{key:'location',label:'Lokalizacja'},{key:'status',label:'Status'},{key:'start',label:'Data rozpoczęcia',type:'date'},{key:'end',label:'Termin zakończenia',type:'date'},{key:'area',label:'Powierzchnia umowna m²',type:'number'},{key:'rate',label:'Stawka zł/m²',type:'number'},{key:'notes',label:'Uwagi',type:'textarea'}]},
buildings:{label:'Budynki',icon:HardHat,editable:true,fields:[{key:'name',label:'Nazwa / numer budynku'},{key:'description',label:'Typ / opis'},{key:'status',label:'Status'},{key:'area',label:'Powierzchnia tynków m²',type:'number'},{key:'start',label:'Termin startu',type:'date'},{key:'end',label:'Termin zakończenia',type:'date'},{key:'siteIds',label:'Budowa',type:'multiselect',options:()=>sites},{key:'notes',label:'Uwagi',type:'textarea'}]},
reports:{label:'Raporty m²',icon:ClipboardList,editable:true,fields:[{key:'name',label:'Raport'},{key:'date',label:'Data',type:'date'},{key:'site',label:'Budowa'},{key:'building',label:'Budynek / etap'},{key:'zone',label:'Strefa'},{key:'meters',label:'Wykonano m²',type:'number'},{key:'people',label:'Liczba osób',type:'number'},{key:'crewIds',label:'Brygada',type:'multiselect',options:()=>crews},{key:'notes',label:'Uwagi',type:'textarea'}]},
problems:{label:'Problemy',icon:FileWarning,editable:true,fields:[{key:'title',label:'Temat'},{key:'date',label:'Data zgłoszenia',type:'date'},{key:'type',label:'Typ'},{key:'priority',label:'Priorytet'},{key:'status',label:'Status'},{key:'responsible',label:'Odpowiedzialny'},{key:'deadline',label:'Termin działania',type:'date'},{key:'description',label:'Opis',type:'textarea'},{key:'resolution',label:'Ustalenia / odpowiedź',type:'textarea'},{key:'siteIds',label:'Budowa',type:'multiselect',options:()=>sites},{key:'crewIds',label:'Brygada',type:'multiselect',options:()=>crews}]},
shifts:{label:'Czas pracy',icon:Clock3,editable:true,fields:[{key:'day',label:'Dzień'},{key:'date',label:'Data',type:'date'},{key:'email',label:'Brygadzista',type:'email'},{key:'start',label:'Start'},{key:'end',label:'Koniec'},{key:'minutes',label:'Minuty',type:'number'},{key:'status',label:'Status'},{key:'crewIds',label:'Brygada',type:'multiselect',options:()=>crews}]},
invoices:{label:'Faktury',icon:Receipt,editable:true,fields:[{key:'number',label:'Numer faktury'},{key:'contractor',label:'Kontrahent'},{key:'issued',label:'Data wystawienia',type:'date'},{key:'due',label:'Termin płatności',type:'date'},{key:'net',label:'Kwota netto',type:'number'},{key:'vat',label:'VAT',type:'number'},{key:'gross',label:'Kwota brutto',type:'number'},{key:'status',label:'Status płatności'},{key:'paid',label:'Data zapłaty',type:'date'},{key:'notes',label:'Uwagi',type:'textarea'},{key:'siteIds',label:'Budowa',type:'multiselect',options:()=>sites}]},
costs:{label:'Koszty',icon:Receipt,editable:true,fields:[{key:'description',label:'Opis kosztu'},{key:'date',label:'Data',type:'date'},{key:'category',label:'Kategoria'},{key:'supplier',label:'Dostawca'},{key:'net',label:'Kwota netto',type:'number'},{key:'gross',label:'Kwota brutto',type:'number'},{key:'paid',label:'Zapłacono',type:'checkbox'},{key:'due',label:'Termin płatności',type:'date'},{key:'notes',label:'Uwagi',type:'textarea'},{key:'siteIds',label:'Budowa',type:'multiselect',options:()=>sites}]}
}),[sites,crews])
async function load(){setLoading(true);try{setData(await api.admin())}catch(e){onMessage((e as Error).message)}finally{setLoading(false)}}useEffect(()=>{load()},[])
const view=views[active],rows=data[active];async function save(){if(!editing)return;setBusy(true);try{const{id,...body}=editing;await api.adminSave(active,body,id||undefined);onMessage('Zmiany zapisane w Airtable.');setEditing(undefined);await load()}catch(e){onMessage((e as Error).message)}finally{setBusy(false)}}
return <section className="content admin-panel"><div className="section-title"><p className="eyebrow">Pełny dostęp administratora</p><h2>Zarządzanie firmą</h2><p>Zmiany zapisują się bezpośrednio w Airtable. Brygadziści nie mają dostępu do tego widoku ani jego API.</p></div><div className="admin-tabs">{(Object.entries(views)as[AdminResource,View][]).map(([key,v])=><button key={key} className={active===key?'active':''} onClick={()=>{setActive(key);setEditing(undefined)}}><v.icon size={18}/>{v.label}<small>{data[key].length}</small></button>)}</div><div className="admin-toolbar"><h3>{view.label}</h3>{view.editable&&<button className="primary" onClick={()=>setEditing({id:''})}><Plus size={17}/>Dodaj</button>}</div>{loading?<p>Ładowanie danych…</p>:rows.length?<div className="admin-table-wrap"><table><thead><tr>{view.fields.slice(0,5).map(f=><th key={f.key}>{f.label}</th>)}<th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}>{view.fields.slice(0,5).map(f=><td key={f.key}>{format(row[f.key],f)}</td>)}<td><button className="table-action" onClick={()=>setEditing({...row})}>Edytuj</button></td></tr>)}</tbody></table></div>:<div className="empty-state"><view.icon/><h3>Brak wpisów</h3><p>Dodaj pierwszy rekord przyciskiem powyżej.</p></div>}{editing&&<div className="editor"><div className="editor-head"><div><p className="eyebrow">{editing.id?'Edycja':'Nowy wpis'}</p><h3>{view.label}</h3></div><button className="iconbtn" onClick={()=>setEditing(undefined)}><X/></button></div><div className="editor-grid">{view.fields.map(f=><EditorField key={f.key} field={f} value={editing[f.key]} onChange={v=>setEditing({...editing,[f.key]:v})}/>)}</div><button className="primary wide" disabled={busy} onClick={save}><Save size={18}/>Zapisz zmiany</button></div>}</section>}

function format(value:unknown,field:Field){if(field.type==='checkbox')return value?'Tak':'Nie';if(Array.isArray(value))return value.length?value.length+' przyp.':'—';return value===undefined||value===null||value===''?'—':String(value)}
function EditorField({field,value,onChange}:{field:Field;value:unknown;onChange:(v:unknown)=>void}){if(field.type==='textarea')return <label>{field.label}<textarea value={String(value||'')} onChange={e=>onChange(e.target.value)}/></label>;if(field.type==='checkbox')return <label className="check"><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/>{field.label}</label>;if(field.type==='multiselect'){const vals=Array.isArray(value)?value as string[]:[];return <label>{field.label}<select multiple value={vals} onChange={e=>onChange(Array.from(e.target.selectedOptions,x=>x.value))}>{field.options?.().map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><small>Możesz zaznaczyć kilka pozycji.</small></label>}return <label>{field.label}<input type={field.type||'text'} value={value===undefined||value===null?'':String(value)} onChange={e=>onChange(field.type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)}/></label>}
