import{useEffect,useMemo,useState}from'react'
import{Bell,Building2,ChevronRight,Clock3,FileCheck2,LayoutDashboard,LogOut,Menu,ShieldCheck,TriangleAlert,Users,X}from'lucide-react'
import{api}from'./api';import type{Bootstrap,Report}from'./types'
import{acceptInvite,handleAuthCallback,login,logout}from'@netlify/identity'
const empty:Report={siteId:'',buildingId:'',crewId:'',squareMeters:0,zone:'',people:1,notes:''}
function elapsed(start?:string){if(!start)return'00:00';const m=Math.max(0,Math.floor((Date.now()-new Date(start).getTime())/60000));return`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`}
function morningReminder(active:boolean){const hour=new Date().getHours(),day=new Date().toISOString().slice(0,10),key=`sebda-reminder-${day}`;if(!active&&hour>=5&&hour<11&&'Notification'in window&&Notification.permission==='granted'&&!localStorage.getItem(key)){new Notification('SEBDA — rozpocznij dzień',{body:'Uruchom licznik pracy swojej brygady.',icon:'/icon.svg'});localStorage.setItem(key,'1')}}
export default function App(){const[data,setData]=useState<Bootstrap>();const[inviteToken,setInviteToken]=useState('');const[page,setPage]=useState<'today'|'report'|'admin'>('today');const[open,setOpen]=useState(false);const[form,setForm]=useState<Report>(empty);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);const[,tick]=useState(0)
useEffect(()=>{(async()=>{try{const callback=await handleAuthCallback();if(callback?.type==='invite'&&callback.token){setInviteToken(callback.token);return}const d=await api.bootstrap();setData(d);setForm(f=>({...f,crewId:d.user.crewId||''}));morningReminder(Boolean(d.activeShift))}catch(e){setMsg((e as Error).message)}})()},[])
useEffect(()=>{const id=setInterval(()=>tick(x=>x+1),30000);return()=>clearInterval(id)},[])
const buildings=useMemo(()=>data?.buildings.filter(x=>x.parentId===form.siteId)||[],[data,form.siteId])
async function start(){setBusy(true);try{const r=await api.start();setData(d=>d&&({...d,activeShift:r.shift}));setMsg('Dzień pracy rozpoczęty. Bezpiecznej pracy!')}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
async function stop(){setBusy(true);try{const r=await api.stop();setData(d=>d&&({...d,activeShift:undefined,todayMinutes:r.minutes}));setPage('report');setMsg('Praca zakończona. Uzupełnij raport m².')}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
async function notify(){if(!('Notification'in window))return setMsg('Ta przeglądarka nie obsługuje powiadomień.');const p=await Notification.requestPermission();setMsg(p==='granted'?'Przypomnienia włączone. Aplikacja przypomni rano po jej uruchomieniu.':'Powiadomienia nie zostały włączone.')}
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api.report(form);setForm({...empty,crewId:data?.user.crewId||''});setPage('today');setMsg('Raport został zapisany w Airtable.')}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
if(inviteToken)return <SetPassword token={inviteToken}/>
if(!data)return msg.startsWith('Zaloguj')?<Login onDone={()=>location.reload()}/>:<main className="loading"><div className="logo">S</div><p>{msg||'Ładowanie bezpiecznego panelu…'}</p></main>
const admin=data.user.role==='admin';const total=(data.todayMinutes+(data.activeShift?Math.floor((Date.now()-new Date(data.activeShift.startedAt).getTime())/60000):0))/60
return <div className="shell"><aside className={open?'expanded':''} onMouseEnter={()=>setOpen(true)} onMouseLeave={()=>setOpen(false)}><button className="mobile-close" onClick={()=>setOpen(false)}><X/></button><div className="brand"><div className="brandmark">S</div><span>SEBDA</span></div><nav><button className={page==='today'?'active':''} onClick={()=>{setPage('today');setOpen(false)}}><LayoutDashboard/><span>Dzisiaj</span></button><button className={page==='report'?'active':''} onClick={()=>{setPage('report');setOpen(false)}}><FileCheck2/><span>Raport m²</span></button>{admin&&<button className={page==='admin'?'active':''} onClick={()=>{setPage('admin');setOpen(false)}}><ShieldCheck/><span>Administracja</span></button>}</nav><div className="aside-bottom"><button onClick={()=>logout().finally(()=>location.reload())}><LogOut/><span>Wyloguj</span></button></div></aside><main><header><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div><p className="eyebrow">{new Intl.DateTimeFormat('pl-PL',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</p><h1>{page==='today'?'Dzień dobry':page==='report'?'Raport dzienny':'Panel administratora'}, {data.user.name.split(' ')[0]}</h1></div><button className="iconbtn" onClick={notify} title="Włącz przypomnienia"><Bell/></button></header>{msg&&<div className="toast" onClick={()=>setMsg('')}>{msg}<X size={16}/></div>}
{page==='today'&&<section className="content"><div className="hero"><div><span className={`status ${data.activeShift?'working':''}`}>{data.activeShift?'Praca trwa':'Dzień nierozpoczęty'}</span><h2>{data.activeShift?'Licznik jest uruchomiony':'Rozpocznij pracę rano'}</h2><p>{data.activeShift?'Czas jest zapisywany dla Twojej brygady. Zakończ po skończonej pracy.':'Jedno kliknięcie uruchomi ewidencję czasu Twojego dnia pracy.'}</p></div><div className="clock">{data.activeShift?elapsed(data.activeShift.startedAt):`${Math.floor(data.todayMinutes/60).toString().padStart(2,'0')}:${(data.todayMinutes%60).toString().padStart(2,'0')}`}<small>godz. : min.</small></div>{data.activeShift?<button className="danger" disabled={busy} onClick={stop}>Zakończ pracę</button>:<button className="primary" disabled={busy} onClick={start}><Clock3/> Rozpocznij dzień</button>}</div><div className="grid"><article><Clock3/><div><small>Dzisiejszy czas</small><strong>{total.toFixed(1)} godz.</strong></div></article><article><Users/><div><small>Twoja brygada</small><strong>{data.crews.find(c=>c.id===data.user.crewId)?.name||'Administrator'}</strong></div></article><article className="action" onClick={()=>setPage('report')}><FileCheck2/><div><small>Po pracy</small><strong>Dodaj raport m²</strong></div><ChevronRight/></article></div><div className="reminder"><Bell/><div><strong>Nie zapomnij rozpocząć dnia</strong><p>Zainstaluj aplikację na ekranie telefonu i włącz powiadomienia. Przypomnienie pojawi się rano po otwarciu PWA.</p></div><button onClick={notify}>Włącz</button></div></section>}
{page==='report'&&<section className="content narrow"><div className="section-title"><p className="eyebrow">Koniec dnia</p><h2>Wykonane prace</h2><p>Wybierz dokładne miejsce i podaj łączną powierzchnię wykonaną dzisiaj.</p></div><form onSubmit={submit}><label>Budowa<select required value={form.siteId} onChange={e=>setForm({...form,siteId:e.target.value,buildingId:''})}><option value="">Wybierz budowę…</option>{data.sites.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Budynek<select required disabled={!form.siteId} value={form.buildingId} onChange={e=>setForm({...form,buildingId:e.target.value})}><option value="">Wybierz budynek…</option>{buildings.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{admin&&<label>Brygada<select required value={form.crewId} onChange={e=>setForm({...form,crewId:e.target.value})}>{data.crews.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}<div className="row"><label>Wykonano m²<input required min="0.1" step="0.1" type="number" value={form.squareMeters||''} onChange={e=>setForm({...form,squareMeters:+e.target.value})}/></label><label>Liczba osób<input required min="1" type="number" value={form.people} onChange={e=>setForm({...form,people:+e.target.value})}/></label></div><label>Kondygnacja / strefa<input value={form.zone} onChange={e=>setForm({...form,zone:e.target.value})} placeholder="np. piętro 2, klatka B"/></label><label>Uwagi<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Materiał, przestój, ważne informacje…"/></label><label>Problem do zgłoszenia (opcjonalnie)<textarea value={form.problem||''} onChange={e=>setForm({...form,problem:e.target.value})} placeholder="Opis problemu zostanie zapisany w osobnym rejestrze"/></label><button className="primary wide" disabled={busy}>Zapisz raport</button></form></section>}
{page==='admin'&&admin&&<section className="content"><div className="section-title"><p className="eyebrow">Pełny dostęp</p><h2>Administracja</h2><p>Widok stawek, rozliczeń, wszystkich brygad i problemów jest dostępny wyłącznie dla administratora. Moduły zarządcze można dołączyć bez zmiany reguł dostępu w API.</p></div><div className="admincards"><article><Users/><small>Brygady</small><strong>{data.crews.length}</strong></article><article><Building2/><small>Budowy</small><strong>{data.sites.length}</strong></article><article><TriangleAlert/><small>Problemy</small><strong>Airtable</strong></article></div></section>}</main></div>}
function Login({onDone}:{onDone:()=>void}){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{await login(email,password);onDone()}catch{setError('Nieprawidłowy e-mail lub hasło.')}finally{setBusy(false)}}return <main className="login"><div className="login-card"><div className="logo">S</div><p className="eyebrow">SEBDA</p><h1>Panel brygadzisty</h1><p>Zaloguj się kontem otrzymanym od administratora.</p><form onSubmit={submit}><label>E-mail<input autoComplete="username" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Hasło<input autoComplete="current-password" type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>Zaloguj się</button></form></div></main>}
function SetPassword({token}:{token:string}){const[password,setPassword]=useState('');const[repeat,setRepeat]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();if(password.length<10)return setError('Hasło musi mieć co najmniej 10 znaków.');if(password!==repeat)return setError('Hasła nie są identyczne.');setBusy(true);try{await acceptInvite(token,password);history.replaceState(null,'',location.pathname);location.reload()}catch{setError('Link wygasł albo został już użyty. Poproś o nowe zaproszenie.');setBusy(false)}}return <main className="login"><div className="login-card"><div className="logo">S</div><p className="eyebrow">Pierwsze logowanie</p><h1>Ustaw swoje hasło</h1><p>Użyj co najmniej 10 znaków. Nie stosuj prostego hasła używanego w innym miejscu.</p><form onSubmit={submit}><label>Nowe hasło<input autoComplete="new-password" type="password" required minLength={10} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Powtórz hasło<input autoComplete="new-password" type="password" required minLength={10} value={repeat} onChange={e=>setRepeat(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>Ustaw hasło i zaloguj</button></form></div></main>}
