import{useEffect,useMemo,useState}from'react'
import{Bell,ChevronRight,FileCheck2,LayoutDashboard,LogOut,Menu,ShieldCheck,Users,X}from'lucide-react'
import{acceptInvite,handleAuthCallback,login,logout,updateUser}from'@netlify/identity'
import{api}from'./api'
import AdminPanel from'./AdminPanel'
import DashboardExtras from'./DashboardExtras'
import type{Bootstrap,Report}from'./types'

const empty:Report={siteId:'',buildingId:'',crewId:'',squareMeters:0,zone:'',people:1,notes:''}
function Brand(){return <div className="brand"><img className="brandmark" src="/brand/sebda-icon.png" alt="SEBDA"/><div className="brandtext"><b>SEBDA</b><small>Tynki maszynowe</small></div></div>}

export default function App(){const[data,setData]=useState<Bootstrap>();const[passwordSetup,setPasswordSetup]=useState<{type:'invite';token:string}|{type:'recovery'}>();const[page,setPage]=useState<'today'|'report'|'admin'>('today');const[open,setOpen]=useState(false);const[form,setForm]=useState<Report>(empty);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
useEffect(()=>{(async()=>{try{const callback=await handleAuthCallback();if(callback?.type==='invite'&&callback.token){setPasswordSetup({type:'invite',token:callback.token});return}if(callback?.type==='recovery'){setPasswordSetup({type:'recovery'});return}const d=await api.bootstrap();setData(d);setForm(f=>({...f,crewId:d.user.crewId||''}))}catch(e){setMsg((e as Error).message)}})()},[])
const buildings=useMemo(()=>data?.buildings.filter(x=>x.parentId===form.siteId)||[],[data,form.siteId])
async function notify(){if(!('Notification'in window))return setMsg('Ta przeglądarka nie obsługuje powiadomień.');const p=await Notification.requestPermission();setMsg(p==='granted'?'Przypomnienia włączone. Aplikacja przypomni rano po jej uruchomieniu.':'Powiadomienia nie zostały włączone.')}
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api.report(form);setForm({...empty,crewId:data?.user.crewId||''});setPage('today');setMsg('Raport został zapisany w Airtable.')}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
if(passwordSetup)return <SetPassword setup={passwordSetup}/>
if(!data)return msg.startsWith('Zaloguj')||msg.startsWith('Konto')?<Login onDone={()=>location.reload()}/>:<main className="loading"><div className="logo">S</div><p>{msg||'Ładowanie bezpiecznego panelu…'}</p></main>
const admin=data.user.role==='admin'
return <div className="shell"><aside className={open?'expanded':''} onMouseEnter={()=>setOpen(true)} onMouseLeave={()=>setOpen(false)}><button className="mobile-close" onClick={()=>setOpen(false)}><X/></button><Brand/><nav><button className={page==='today'?'active':''} onClick={()=>{setPage('today');setOpen(false)}}><LayoutDashboard/><span>Dzisiaj</span></button><button className={page==='report'?'active':''} onClick={()=>{setPage('report');setOpen(false)}}><FileCheck2/><span>Raport m²</span></button>{admin&&<button className={page==='admin'?'active':''} onClick={()=>{setPage('admin');setOpen(false)}}><ShieldCheck/><span>Administracja</span></button>}</nav><div className="aside-bottom"><button onClick={()=>logout().finally(()=>location.reload())}><LogOut/><span>Wyloguj</span></button></div></aside><main><header><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div><p className="eyebrow">{new Intl.DateTimeFormat('pl-PL',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</p><h1>{page==='today'?'Dzień dobry':page==='report'?'Raport dzienny':'Panel administratora'}, {data.user.name.split(' ')[0]}</h1></div><button className="iconbtn" onClick={notify} title="Włącz przypomnienia"><Bell/></button></header>{msg&&<div className="toast" onClick={()=>setMsg('')}>{msg}<X size={16}/></div>}

{page==='today'&&<DashboardExtras role={data.user.role} onMessage={setMsg}/>}
{page==='today'&&<section className="content"><div className="hero"><div><span className="status working">Rozliczenie za m²</span><h2>Dodaj wykonane metry</h2><p>Każda brygada zapisuje dzienny raport wykonanych m². Godziny pracy nie są rozliczane.</p></div><button className="primary" onClick={()=>setPage('report')}><FileCheck2/> Dodaj raport m²</button></div><div className="grid"><article><Users/><div><small>Twoja brygada</small><strong>{data.crews.find(c=>c.id===data.user.crewId)?.name||'Administrator'}</strong></div></article><article className="action" onClick={()=>setPage('report')}><FileCheck2/><div><small>Po pracy</small><strong>Dodaj raport m²</strong></div><ChevronRight/></article></div></section>}
{page==='report'&&<section className="content narrow"><div className="section-title"><p className="eyebrow">Koniec dnia</p><h2>Wykonane prace</h2><p>Wybierz dokładne miejsce i podaj łączną powierzchnię wykonaną dzisiaj.</p></div><form onSubmit={submit}><label>Budowa<select required value={form.siteId} onChange={e=>setForm({...form,siteId:e.target.value,buildingId:''})}><option value="">Wybierz budowę…</option>{data.sites.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Budynek<select required disabled={!form.siteId} value={form.buildingId} onChange={e=>setForm({...form,buildingId:e.target.value})}><option value="">Wybierz budynek…</option>{buildings.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{admin&&<label>Brygada<select required value={form.crewId} onChange={e=>setForm({...form,crewId:e.target.value})}><option value="">Wybierz brygadę…</option>{data.crews.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}<div className="row"><label>Wykonano m²<input required min="0.1" step="0.1" type="number" value={form.squareMeters||''} onChange={e=>setForm({...form,squareMeters:+e.target.value})}/></label><label>Liczba osób<input required min="1" type="number" value={form.people} onChange={e=>setForm({...form,people:+e.target.value})}/></label></div><label>Kondygnacja / strefa<input value={form.zone} onChange={e=>setForm({...form,zone:e.target.value})} placeholder="np. piętro 2, klatka B"/></label><label>Uwagi<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label>Problem do zgłoszenia (opcjonalnie)<textarea value={form.problem||''} onChange={e=>setForm({...form,problem:e.target.value})}/></label><button className="primary wide" disabled={busy}>Zapisz raport</button></form></section>}
{page==='admin'&&admin&&<AdminPanel sites={data.sites} crews={data.crews} onMessage={setMsg}/>}<footer><strong>Kontakt {data.contact.company}</strong><span><a href={`mailto:${data.contact.email}`}>{data.contact.email}</a>{data.contact.phone&&<> · <a href={`tel:${data.contact.phone.replaceAll(' ','')}`}>{data.contact.phone}</a></>}</span></footer></main></div>}

function Login({onDone}:{onDone:()=>void}){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{await login(email,password);onDone()}catch{setError('Nieprawidłowy e-mail lub hasło.')}finally{setBusy(false)}}return <main className="login"><div className="login-card"><div className="logo">S</div><p className="eyebrow">SEBDA · Tynki i budownictwo</p><h1>Panel pracownika</h1><p>Zaloguj się kontem otrzymanym od administratora.</p><form onSubmit={submit}><label>E-mail<input autoComplete="username" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Hasło<input autoComplete="current-password" type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>Zaloguj się</button></form><div className="login-contact">Kontakt SEBDA: <a href="tel:790495208">790 495 208</a> · <a href="mailto:sebdafirma@gmail.com">e-mail</a></div></div></main>}
function SetPassword({setup}:{setup:{type:'invite';token:string}|{type:'recovery'}}){const[password,setPassword]=useState('');const[repeat,setRepeat]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();if(password.length<6)return setError('Hasło musi mieć co najmniej 6 znaków.');if(password!==repeat)return setError('Hasła nie są identyczne.');setBusy(true);try{if(setup.type==='invite')await acceptInvite(setup.token,password);else await updateUser({password});history.replaceState(null,'',location.pathname);location.reload()}catch{setError('Link wygasł albo został już użyty. Poproś administratora o nowy link.');setBusy(false)}}return <main className="login"><div className="login-card"><div className="logo">S</div><p className="eyebrow">{setup.type==='invite'?'Pierwsze logowanie':'Odzyskiwanie dostępu'}</p><h1>Ustaw swoje hasło</h1><p>Użyj co najmniej 6 znaków. Nie stosuj prostego hasła używanego w innym miejscu.</p><form onSubmit={submit}><label>Nowe hasło<input autoComplete="new-password" type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Powtórz hasło<input autoComplete="new-password" type="password" required minLength={6} value={repeat} onChange={e=>setRepeat(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>Ustaw hasło i zaloguj</button></form></div></main>}
