import{useEffect,useState}from'react'
import{Activity,ChevronRight,Share2,Users,X}from'lucide-react'
import{api}from'./api'
import{makeReportPdf,saveOrSharePdf}from'./pdf'
import HistoryPanel from'./HistoryPanel'
import type{CompanyOverview,Role}from'./types'
const iso=(d:Date)=>d.toISOString().slice(0,10)
export default function DashboardExtras({role,onMessage}:{role:Role;onMessage:(s:string)=>void}){const today=new Date(),start=new Date(today.getFullYear(),today.getMonth(),1);const[from,setFrom]=useState(iso(start)),[to,setTo]=useState(iso(today)),[overview,setOverview]=useState<CompanyOverview>(),[selectedCrew,setSelectedCrew]=useState<string>(),[selectedHelper,setSelectedHelper]=useState<string>(),[busy,setBusy]=useState(false)
useEffect(()=>{document.body.dataset.role=role;if(role!=='admin')return;const load=()=>api.overview().then(setOverview).catch(e=>onMessage((e as Error).message));load();const id=setInterval(load,60000);return()=>clearInterval(id)},[role])
async function pdf(){setBusy(true);try{if(role==='admin'){if(!selectedCrew)return onMessage('Najpierw wybierz brygadę.');const r=await api.crewReport(selectedCrew,from,to),rows=r.rows.map(x=>({...x,description:`${x.description} | zarobek ${Number(x.earnings||0).toFixed(2)} zl`}));await saveOrSharePdf(makeReportPdf(`${r.title} | zarobek ${r.totals.earnings.toFixed(2)} zl | pomocnicy ${r.totals.helperCost.toFixed(2)} zl`,r.from,r.to,rows,r.totals),`SEBDA-${r.title.replace(/\W+/g,'-')}-${from}-${to}.pdf`)}else{const r=await api.personalReport(from,to);await saveOrSharePdf(makeReportPdf(r.title,r.from,r.to,r.rows,r.totals),`SEBDA-raport-${from}-${to}.pdf`)}}catch(e){onMessage((e as Error).message)}finally{setBusy(false)}}
if(role!=='admin')return <section className="content extras"><ReportBox from={from} to={to} setFrom={setFrom} setTo={setTo} busy={busy} onPdf={pdf} title="Twój raport"/><HistoryPanel role={role} from={from} to={to} onMessage={onMessage}/></section>
const crew=overview?.crews.find(x=>x.id===selectedCrew),helper=overview?.helpers.find(x=>x.id===selectedHelper)
return <section className="content extras admin-extras"><div className="live-box"><div className="section-title"><p className="eyebrow">Aktualizacja co minutę</p><h2><Activity/>Firma na żywo</h2><p>Kliknij brygadę albo pomocnika, aby zobaczyć szczegóły.</p></div><h3>Brygady</h3><div className="click-grid">{overview?.crews.map(x=><button key={x.id} onClick={()=>{setSelectedCrew(x.id);setSelectedHelper(undefined)}}><span className={`live-dot ${x.active?'on':''}`}/><div><strong>{x.name}</strong><small>{x.site||'Brak wskazanej budowy'} · {x.hours.toFixed(1)} h · {x.meters.toFixed(1)} m²</small></div><ChevronRight/></button>)}</div><h3>Pomocnicy</h3><div className="click-grid">{overview?.helpers.map(x=><button key={x.id} onClick={()=>{setSelectedHelper(x.id);setSelectedCrew(undefined)}}><span className={`live-dot ${x.active?'on':''}`}/><div><strong>{x.name}</strong><small>{x.site||'Dzisiaj bez budowy'} · {x.hours.toFixed(1)} h</small></div><ChevronRight/></button>)}</div></div>{crew&&<Detail title={crew.name} onClose={()=>setSelectedCrew(undefined)} rows={[['Brygadzista',crew.foreman],['Status',crew.active?'Pracuje teraz':'Nieaktywny'],['Budowa',crew.site||'—'],['Start',crew.startedAt?new Date(crew.startedAt).toLocaleTimeString('pl-PL'):'—'],['Dzisiejsze godziny',`${crew.hours.toFixed(2)} h`],['Wykonano',`${crew.meters.toFixed(2)} m²`],['Zarobek brygady',`${crew.earnings.toFixed(2)} zł`],['Godziny pomocników',`${crew.helperHours.toFixed(2)} h`],['Koszt pomocników',`${crew.helperCost.toFixed(2)} zł`],['Pomocnicy',crew.helpers.join(', ')||'—']]}/>} {helper&&<Detail title={helper.name} onClose={()=>setSelectedHelper(undefined)} rows={[['Login',helper.email],['Status',helper.active?'Pracuje teraz':'Nieaktywny'],['Budowa',helper.site||'—'],['Start',helper.startedAt?new Date(helper.startedAt).toLocaleTimeString('pl-PL'):'—'],['Dzisiejsze godziny',`${helper.hours.toFixed(2)} h`],['Stawka',`${helper.rate.toFixed(2)} zł/h`],['Dzisiejszy koszt',`${helper.cost.toFixed(2)} zł`]]}/>}<ReportBox from={from} to={to} setFrom={setFrom} setTo={setTo} busy={busy} onPdf={pdf} title={crew?`Raport: ${crew.name}`:'Wybierz brygadę do raportu'} disabled={!crew}/><HistoryPanel role={role} crewId={selectedCrew} from={from} to={to} onMessage={onMessage}/></section>}
function Detail({title,rows,onClose}:{title:string;rows:[string,string][];onClose:()=>void}){return <div className="detail-card"><button className="iconbtn" onClick={onClose}><X/></button><h3>{title}</h3><dl>{rows.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div>}
function ReportBox({from,to,setFrom,setTo,busy,onPdf,title,disabled}:{from:string;to:string;setFrom:(s:string)=>void;setTo:(s:string)=>void;busy:boolean;onPdf:()=>void;title:string;disabled?:boolean}){return <div className="personal-report"><div><p className="eyebrow">Raport PDF</p><h3><Share2/>{title}</h3><p>Raport zawiera wyłącznie daty, godziny, m² i rozliczenie wybranej brygady.</p></div><div className="report-range"><label>Od<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Do<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="primary" disabled={busy||disabled} onClick={onPdf}><Share2 size={17}/>Generuj PDF</button></div></div>}
