import{useEffect,useState}from'react'
import{Activity,Share2}from'lucide-react'
import{api}from'./api'
import{makeReportPdf,saveOrSharePdf}from'./pdf'
import type{LiveDashboard,Role}from'./types'
const iso=(d:Date)=>d.toISOString().slice(0,10)
export default function DashboardExtras({role,onMessage}:{role:Role;onMessage:(s:string)=>void}){const today=new Date(),start=new Date(today.getFullYear(),today.getMonth(),1);const[from,setFrom]=useState(iso(start)),[to,setTo]=useState(iso(today)),[live,setLive]=useState<LiveDashboard>(),[busy,setBusy]=useState(false)
useEffect(()=>{if(role!=='admin')return;const load=()=>api.live().then(setLive).catch(e=>onMessage((e as Error).message));load();const id=setInterval(load,60000);return()=>clearInterval(id)},[role])
async function pdf(){setBusy(true);try{if(role==='admin'){const r=await api.summary(from,to),rows=r.rows.map(x=>({date:x.date,description:`${x.type} ${x.person} ${x.crew} ${x.site}`,hours:x.hours,meters:x.meters}));await saveOrSharePdf(makeReportPdf('SEBDA - raport firmy',r.from,r.to,rows,{hours:r.totals.foremanHours+r.totals.helperHours,meters:r.totals.meters}),`SEBDA-raport-firmy-${from}-${to}.pdf`)}else{const r=await api.personalReport(from,to);await saveOrSharePdf(makeReportPdf(r.title,r.from,r.to,r.rows,r.totals),`SEBDA-raport-${from}-${to}.pdf`)}}catch(e){onMessage((e as Error).message)}finally{setBusy(false)}}
return <section className="content extras">{role==='admin'&&live&&<div className="live-box"><div className="section-title"><p className="eyebrow">Aktualizacja co minutę</p><h2><Activity/>Firma na żywo</h2></div><div className="summary-cards"><article><small>Aktywne osoby</small><strong>{live.counts.active}</strong></article><article><small>Brygady</small><strong>{live.counts.crews}</strong></article><article><small>Pomocnicy</small><strong>{live.counts.helpers}</strong></article><article><small>Budowy</small><strong>{live.counts.sites}</strong></article><article><small>Dzisiaj</small><strong>{live.today.hours.toFixed(1)} h · {live.today.meters.toFixed(1)} m²</strong></article></div><div className="live-list">{live.active.length?live.active.map((x,i)=><article key={i}><Activity/><div><strong>{x.person}</strong><small>{x.role} · {x.crew||'bez brygady'} · {x.site||'budowa niepodana'} · od {new Date(x.startedAt).toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'})}</small></div></article>):<p>Nikt obecnie nie ma uruchomionego licznika.</p>}</div></div>}<div className="personal-report"><div><p className="eyebrow">{role==='admin'?'Raport całej firmy':'Twój raport'}</p><h3><Share2/>Zapisz lub wyślij PDF</h3><p>Na telefonie otworzy się systemowe udostępnianie, gdzie możesz wybrać e-mail. Na komputerze plik PDF zostanie zapisany.</p></div><div className="report-range"><label>Od<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Do<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="primary" disabled={busy} onClick={pdf}><Share2 size={17}/>Generuj PDF</button></div></div></section>}
